import PreCruiseStay, {hotelAdvice} from "@/components/PreCruiseStay";
import {Link, useRoute} from "wouter";
import SiteShell from "@/components/SiteShell";
import ApprovedOfferArt from "@/components/ApprovedOfferArt";
import {cruiseOffers,offerInquiryHref} from "@/lib/cruiseOffers";
import {offerDetails, conquestCabinDescriptions, springCabinDescriptions} from "@/lib/offerDetails";
import NotFound from "./NotFound";
import "./OfferCollection.css";
export default function OfferDetail(){
 const [,params]=useRoute("/offers/:slug"); const o=cruiseOffers.find(o=>o.slug===params?.slug);
 const d=offerDetails[params?.slug as keyof typeof offerDetails];
 if(!o||!d)return <NotFound/>;
 const inquiry=offerInquiryHref(o.id); const val=o.art==="valentines";
 const shipHref=o.art==="mardi"?"https://www.carnival.com/cruise-ships/mardi-gras":o.art==="pride"?"https://www.carnival.com/cruise-ships/carnival-pride":"https://www.carnival.com/cruise-ships/carnival-conquest";
 const cabinPhotos: Record<string,string> = val ? {Interior:"conquest-interior.jpg", "Ocean View":"conquest-ocean-view.jpg", Balcony:"conquest-balcony.jpg"} : o.art==="mardi" ? {Interior:"mardi-interior.jpg", "Ocean View":"mardi-ocean-view.jpg", "Cove Balcony":"mardi-cove-balcony.jpg"} : {};
 const jumpTo = (id:string) => { const section=document.getElementById(id); section?.scrollIntoView({behavior:"instant",block:"start"}); section?.focus({preventScroll:true}); };
 const journey=o.art==="pride"?"Leave the everyday behind with seven nights aboard Carnival Pride, departing Baltimore March 14–21, 2027. Gather your favorite people and make time for a spring break together.":"Set sail from Port Canaveral for seven nights of Caribbean discovery aboard Carnival Mardi Gras. Explore Nassau, RelaxAway Half Moon Cay, Amber Cove, and Celebration Key, with days at sea to enjoy your own pace.";

 return <SiteShell darkHeader><div className={`twco-collection-page twco-detail-page twco-detail--${o.art}`}>
 <div className="twco-detail-wrap twco-detail-back"><Link href="/offers">← Current Offers</Link></div>
 <div className="twco-mobile-sailing"><strong>Departing {o.port}</strong><span>{o.ship} · {o.dates}</span></div><section className="twco-detail-wrap twco-detail-hero"><div className="twco-detail-art"><a href="#cabins" onClick={event=>{event.preventDefault();jumpTo("cabins");}} aria-label={`See stateroom options for ${o.title}`}><ApprovedOfferArt art={o.art} title={o.title}/></a></div><div className="twco-detail-intro"><p className="twco-collection-eyebrow">The 2027 cruise collection</p><h1>{o.title}</h1><p className="twco-detail-lead">{d.lead}</p><p>{o.summary}</p><div className="twco-detail-port"><span>Departure & return</span><strong>{o.port}</strong></div><dl className="twco-detail-facts"><div><dt>Your ship</dt><dd>{o.ship}</dd></div><div><dt>Your dates</dt><dd>{o.dates}</dd></div><div><dt>Time away</dt><dd>{o.nights} nights</dd></div></dl><Link className="twco-collection-button" href={inquiry}>Plan this voyage <span aria-hidden="true">↗</span></Link><p className="twco-detail-small">Current pricing by inquiry. Wendy will confirm the details before you book.</p></div></section>
 <nav className="twco-detail-nav" aria-label="On this offer page"><a href="#journey" onClick={event=>{event.preventDefault();jumpTo("journey");}}>The journey</a><a href={shipHref} target="_blank" rel="noopener noreferrer">See the ship ↗</a><a href="#cabins" onClick={event=>{event.preventDefault();jumpTo("cabins");}}>Cabin options</a>{val&&<a href="#game-day" onClick={event=>{event.preventDefault();jumpTo("game-day");}}>Game day</a>}<a href="#details" onClick={event=>{event.preventDefault();jumpTo("details");}}>Booking with Wendy</a><a href="#before-you-sail" onClick={event=>{event.preventDefault();jumpTo("before-you-sail");}}>Hotels before sailing</a><a href="#questions" onClick={event=>{event.preventDefault();jumpTo("questions");}}>Good to know</a><a href="#inquiry" onClick={event=>{event.preventDefault();jumpTo("inquiry");}}>Inquire</a></nav>
 <section id="journey" tabIndex={-1} className="twco-detail-wrap twco-detail-section"><div className="twco-detail-section-title"><p className="twco-collection-eyebrow">Your journey</p><h2>A little closer to <em>getting away.</em></h2></div><div><p>{val?"Set sail from Miami for a three-night Valentine’s escape, with a day to enjoy life at sea and Valentine’s Day in Celebration Key. Return with shared memories and a little more time together.":journey}</p>{d.itinerary.length?<div className="twco-detail-itinerary">{d.itinerary.map(([date,port,time])=><div key={date}><span>{date}</span><strong>{port}</strong><span>{time||"Time at sea"}</span></div>)}</div>:<div className="twco-detail-verification"><strong>Your spring break, personally planned</strong><p>Connect with Wendy for the latest sailing itinerary and help planning your time away.</p><Link href={inquiry} className="twco-detail-text-link">Request your sailing itinerary ↗</Link></div>}<p className="twco-detail-small">Itinerary and port times are subject to change.</p></div></section>
 <section id="cabins" tabIndex={-1} className="twco-detail-tinted"><div className="twco-detail-wrap twco-detail-section"><div className="twco-detail-section-title"><p className="twco-collection-eyebrow">Your space at sea</p><h2>Find your <em>comfortable fit.</em></h2></div><div><p>{val?"Make your weekend your own. Choose a cozy retreat, a view of the sea, or a balcony made for lingering a little longer.":"Choose the space that suits your travel style. Wendy will help you compare staterooms, views, and available locations for your sailing."}</p><div className="twco-detail-cabins">{d.cabins.map(c=><div key={c}>{cabinPhotos[c] && <figure className="twco-cabin-photo"><img src={`/images/offers/cabins/${cabinPhotos[c]}`} alt={`${o.ship} ${c} stateroom — representative Carnival photo`} loading="lazy"/><figcaption>Representative {o.ship} {c} · layouts vary by stateroom</figcaption></figure>}<h3>{c}</h3><p>{val?conquestCabinDescriptions[c]:springCabinDescriptions[c]}</p><Link href={`${inquiry}&cabin=${encodeURIComponent(c)}`} className="twco-detail-text-link">Ask Wendy about this stateroom ↗</Link></div>)}</div>{val&&<p className="twco-detail-small">Wendy will help you choose your stateroom and check current availability.</p>}<Link href={inquiry} className="twco-detail-text-link">Ask Wendy to compare stateroom options ↗</Link></div></div></section>
 {val&&<section className="twco-detail-wrap twco-detail-section"><div className="twco-detail-section-title"><p className="twco-collection-eyebrow">Valentine’s Weekend only</p><h2>A celebration <em>for two. Or a few.</em></h2></div><div><p>A little something to celebrate your time together: enjoy champagne and chocolates on embarkation day, plus house wine on Valentine’s Day.</p><p className="twco-detail-small">These special touches are part of The Wendy Collective’s Valentine’s Weekend offer.</p></div></section>}
 {val&&<section id="game-day" tabIndex={-1} className="twco-detail-tinted"><div className="twco-detail-wrap twco-detail-section"><div className="twco-detail-section-title"><p className="twco-collection-eyebrow">Valentine’s Day meets game day · February 14, 2027</p><h2>Your Valentine.<br/>Your team.<br/><em>Your weekend.</em></h2></div><div><p>Celebrate love and football’s biggest Sunday aboard Carnival Conquest. Bring your favorite person—or your favorite people—for a weekend with even more to look forward to.</p><ul className="twco-detail-client-list"><li>Tailgate parties to get into the game-day spirit.</li><li>A team-spirit scavenger hunt.</li><li>Super Bowl viewing with fellow football fans.</li></ul><p>Viewing venues may include select bars, the Carnival Seaside Theater on Lido, and the main lounge.</p><p className="twco-detail-small">Locations vary, and broadcasts are subject to change. Once onboard, check the Carnival HUB app for confirmed venues, activities, and schedules.</p></div></div></section>}
 <section id="details" tabIndex={-1} className="twco-detail-wrap twco-detail-section"><div className="twco-detail-section-title"><p className="twco-collection-eyebrow">Clear details, personal guidance</p><h2>Before you <em>say yes.</em></h2></div><div><p>Enjoy the anticipation. Wendy will guide you through the details, help you choose your stateroom, and prepare a personalized quote.</p><ul className="twco-detail-client-list"><li>Compare available staterooms and current fares.</li><li>Understand your total price, including applicable taxes and fees.</li><li>Review your deposit, payment schedule, and cancellation terms before booking.</li></ul><Link href={inquiry} className="twco-detail-text-link">Request your personalized quote ↗</Link></div></section>
 <PreCruiseStay inquiry={inquiry}/>
 <section id="questions" tabIndex={-1} className="twco-detail-tinted"><div className="twco-detail-wrap twco-detail-section"><div className="twco-detail-section-title"><p className="twco-collection-eyebrow">Good to know</p><h2>A few <em>helpful answers.</em></h2></div><div className="twco-detail-faq"><details><summary>Where does this cruise depart?</summary><p>{val?"The Carnival Conquest sailing is February 12-15 and departs from and returns to Miami, Florida.":o.art==="mardi"?"The Carnival Mardi Gras sailing is March 13–20, 2027 and departs from and returns to Port Canaveral, Florida.":"The Carnival Pride sailing is March 14–21, 2027 and departs from and returns to Baltimore, Maryland."}</p></details><details><summary>What is the current price?</summary><p>Request a personalized quote from Wendy with available staterooms, current fares, applicable taxes and fees, and payment options.</p></details>{val?<details><summary>How do I choose my stateroom?</summary><p>Tell Wendy whether you prefer Interior, Ocean View, or Balcony. She will help you compare available options for your weekend.</p></details>:<details><summary>How can I get the full sailing itinerary?</summary><p>Ask Wendy for the latest itinerary, port times, and help coordinating your travel to the ship.</p></details>}{val&&<details><summary>Can we watch the Super Bowl onboard?</summary><p>Yes. Carnival Conquest plans Super Bowl viewing, tailgate parties, and a team-spirit scavenger hunt for this sailing. Viewing venues may include select bars, the Carnival Seaside Theater on Lido, and the main lounge. Locations vary, and broadcasts are subject to change. Check the Carnival HUB app once onboard for confirmed venues and schedules.</p></details>}<details><summary>Can Wendy help with a hotel before the cruise?</summary><p>{hotelAdvice} Hotel stays are arranged separately from your cruise fare.</p></details><details><summary>Does an inquiry reserve a stateroom?</summary><p>No. Your inquiry begins a conversation with Wendy. It does not reserve a stateroom, take payment or lock in a fare.</p></details></div></div></section>
 <section id="inquiry" tabIndex={-1} className="twco-detail-inquiry"><div className="twco-detail-wrap"><p className="twco-collection-eyebrow">Thoughtfully planned, personally yours</p><h2>Let’s make this <em>your next chapter.</em></h2><p>{o.ship} · {o.dates}<br/><strong>Departing {o.port}</strong></p><Link href={inquiry} className="twco-collection-button">Start my inquiry with Wendy ↗</Link><p className="twco-detail-small">Your selected offer and dates will be included in the inquiry form.</p></div></section>
 <nav className="twco-detail-wrap twco-detail-other" aria-label="Explore the other offers">{cruiseOffers.filter(other=>other.id!==o.id).map(other=><Link key={other.id} href={`/offers/${other.slug}`}>{other.title} ↗</Link>)}</nav>
 </div></SiteShell>;
}
