import {Link} from "wouter";
import SiteShell from "@/components/SiteShell";
import ApprovedOfferArt from "@/components/ApprovedOfferArt";
import {cruiseOffers} from "@/lib/cruiseOffers";
import "./OfferCollection.css";
export default function Offers(){return <SiteShell darkHeader><div className="twco-collection-page">
 <header className="twco-collection-hero"><div className="twco-reference-masthead" aria-hidden="true"><img src="/images/offers/approved-landing-reference.png" width="1536" height="1024" alt=""/></div><p className="twco-collection-eyebrow">The Wendy Collective · Curated journeys. Beautifully lived.</p><h1>Current Offers</h1><p className="twco-collection-script">Extraordinary getaways. Exceptional possibilities.</p><p className="twco-collection-categories">Cruises <span>✦</span> Destination weddings <span>✦</span> All-inclusive resorts <span>✦</span> More</p></header>
 <section className="twco-collection-wrap" aria-label="Four featured cruise offers"><div className="twco-collection-grid">{cruiseOffers.map(o=><article className={`twco-collection-card twco-collection-card--${o.art}`} key={o.id}><Link className="twco-collection-art-link" href={`/offers/${o.slug}`} aria-label={`View ${o.title}`}><div className="twco-collection-ribbon">{o.season==="March"?"Spring Break 2027":o.season==="July"?"An Alaska escape":"Valentine’s Weekend"}</div><div className="twco-departure-ribbon">Departing {o.port}</div><div className="twco-collection-art-stage"><ApprovedOfferArt art={o.art} title={o.title}/></div></Link><div className="twco-collection-card-copy"><h2><Link href={`/offers/${o.slug}`}>{o.title}</Link></h2><p>{o.ship}</p><p className="twco-collection-date">{o.dates}</p><div className="twco-collection-port"><span>Departure</span><strong>{o.port}</strong></div><Link className="twco-collection-button" href={`/offers/${o.slug}`}>View details <span aria-hidden="true">↗</span></Link></div></article>)}</div></section>
 <section className="twco-collection-wrap twco-collection-more" aria-label="More ways to travel"><Link href="/destinations/all-inclusive"><span>Unwind your way</span><h2>All-Inclusive<br/>Resorts</h2><span>Explore escapes ↗</span></Link><Link href="/contact?type=group"><span>Beautiful places. Meaningful moments.</span><h2>Destination<br/>Weddings</h2><span>Plan with Wendy ↗</span></Link><Link href="/contact"><span>Made around you</span><h2>Custom<br/>Getaways</h2><span>Share your vision ↗</span></Link></section>
 <div className="twco-collection-values twco-collection-wrap"><span>✧ Expert planning</span><span>♡ Personalized service</span><span>✦ Thoughtful details</span><span>◎ Curated destinations</span></div><p className="twco-collection-bottom">Current fares and availability by inquiry. An inquiry does not reserve a cabin or confirm a price.</p>
 </div></SiteShell>}
