import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import SiteShell from "@/components/SiteShell";
import { trpc } from "@/lib/trpc";

type Traveler = { fullName: string; dateOfBirth: string; loyaltyNumber: string };
const blankTraveler = (): Traveler => ({ fullName: "", dateOfBirth: "", loyaltyNumber: "" });

export default function TravelerProfileView() {
  const [location] = useLocation();
  const token = location.split("/").filter(Boolean).at(-1) || "";
  const profile = trpc.crm.getTravelerProfile.useQuery({ token }, { enabled: token.length >= 32 });
  const submit = trpc.crm.submitTravelerProfile.useMutation();
  const [contact, setContact] = useState<{ firstName: string; lastName: string; email: string; phone: string; notes: string; consent: boolean }>({ firstName: "", lastName: "", email: "", phone: "", notes: "", consent: false });
  const [travelers, setTravelers] = useState<Traveler[]>([blankTraveler()]);
  const [preferences, setPreferences] = useState({ destinationIdeas: "", travelWindow: "", departurePort: "", budgetDirection: "", roomPreferences: "", paceAndStyle: "", accessibilityNeeds: "", mustHaves: "" });

  useEffect(() => {
    if (!profile.data) return;
    const { deal } = profile.data;
    setContact((current) => ({ ...current, firstName: deal.contactFirstName, lastName: deal.contactLastName, email: deal.email, phone: deal.phone }));
  }, [profile.data]);

  if (profile.isLoading) return <SiteShell darkHeader><main className="proposal-loading">Preparing your traveler profile.</main></SiteShell>;
  if (!profile.data) return <SiteShell darkHeader><main className="proposal-loading">This private traveler profile is no longer available. Please contact Wendy for a current link.</main></SiteShell>;
  if (submit.data?.success) return <SiteShell darkHeader><section className="page-hero"><div className="page-wrap"><p className="eyebrow">Thank you</p><h1 className="display">Wendy has your travel <em>details.</em></h1><p className="body-copy">Your preferences are saved with your private request. Wendy will use them to prepare thoughtful options, then reach out to review the next step.</p></div></section></SiteShell>;

  const updateTraveler = (index: number, field: keyof Traveler, value: string) => setTravelers((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, [field]: value } : item));
  return <SiteShell darkHeader><section className="proposal-hero"><div className="page-wrap"><p className="eyebrow">A private traveler profile</p><h1 className="display">Let’s make your next trip <em>personal.</em></h1><p>{profile.data.deal.title}</p><div className="proposal-hero__details"><span>Prepared for {profile.data.deal.contactFirstName} {profile.data.deal.contactLastName}</span><span>Wendy will personally confirm every option and quote.</span></div></div></section>
    <section className="page-section page-section--warm"><div className="page-wrap proposal-layout"><aside><p className="eyebrow">Your next step</p><h2 className="display display--small">Tell Wendy what matters most.</h2><p className="body-copy">Share your travel party and preferences. This does not reserve travel, quote a fare, or collect payment. Wendy will research options personally and confirm live details with you.</p><p className="form-help">Do not enter payment cards, passport details, account passwords, or medical information.</p></aside><form className="school-request-form" onSubmit={(event) => { event.preventDefault(); if (!contact.consent) return; submit.mutate({ token, contactFirstName: contact.firstName, contactLastName: contact.lastName, email: contact.email, phone: contact.phone, travelerDetails: travelers, preferences, notes: contact.notes, consent: true }); }}>
      <div className="form-intro"><h2>Your traveler profile</h2><p>These details help Wendy narrow down the right cruise, resort, tour, or tailored trip.</p></div>
      <div className="form-grid"><Field id="traveler-first" label="First name" value={contact.firstName} onChange={(value) => setContact({ ...contact, firstName: value })} required /><Field id="traveler-last" label="Last name" value={contact.lastName} onChange={(value) => setContact({ ...contact, lastName: value })} required /><Field id="traveler-email" label="Email" type="email" value={contact.email} onChange={(value) => setContact({ ...contact, email: value })} required /><Field id="traveler-phone" label="Phone" value={contact.phone} onChange={(value) => setContact({ ...contact, phone: value })} required /><Field id="traveler-destinations" label="Destination ideas" value={preferences.destinationIdeas} onChange={(value) => setPreferences({ ...preferences, destinationIdeas: value })} required wide /><Field id="traveler-window" label="Ideal travel window" value={preferences.travelWindow} onChange={(value) => setPreferences({ ...preferences, travelWindow: value })} required /><Field id="traveler-port" label="Preferred departure airport or port" value={preferences.departurePort} onChange={(value) => setPreferences({ ...preferences, departurePort: value })} /><Field id="traveler-budget" label="Budget direction" value={preferences.budgetDirection} onChange={(value) => setPreferences({ ...preferences, budgetDirection: value })} wide /><Field id="traveler-style" label="Pace and travel style" value={preferences.paceAndStyle} onChange={(value) => setPreferences({ ...preferences, paceAndStyle: value })} text wide /><Field id="traveler-rooms" label="Room and cabin preferences" value={preferences.roomPreferences} onChange={(value) => setPreferences({ ...preferences, roomPreferences: value })} text wide /><Field id="traveler-must-haves" label="Must haves" value={preferences.mustHaves} onChange={(value) => setPreferences({ ...preferences, mustHaves: value })} text wide /><Field id="traveler-access" label="Accessibility or mobility notes" value={preferences.accessibilityNeeds} onChange={(value) => setPreferences({ ...preferences, accessibilityNeeds: value })} text wide /></div>
      <div className="school-rooms"><h3>Who is traveling?</h3>{travelers.map((traveler, index) => <fieldset className="school-room" key={index}><legend>Traveler {index + 1}</legend><div className="form-grid"><Field id={`profile-name-${index}`} label="Legal full name" value={traveler.fullName} onChange={(value) => updateTraveler(index, "fullName", value)} required wide /><Field id={`profile-birth-${index}`} label="Date of birth" type="date" value={traveler.dateOfBirth} onChange={(value) => updateTraveler(index, "dateOfBirth", value)} /><Field id={`profile-loyalty-${index}`} label="Loyalty number if available" value={traveler.loyaltyNumber} onChange={(value) => updateTraveler(index, "loyaltyNumber", value)} /></div>{travelers.length > 1 && <button type="button" className="school-room__remove" onClick={() => setTravelers((items) => items.filter((_, itemIndex) => itemIndex !== index))}>Remove traveler</button>}</fieldset>)}</div><button type="button" className="school-add-room" onClick={() => setTravelers((items) => [...items, blankTraveler()])} disabled={travelers.length >= 12}>Add traveler <span aria-hidden="true">+</span></button><Field id="traveler-notes" label="Anything else Wendy should know?" value={contact.notes} onChange={(value) => setContact({ ...contact, notes: value })} text wide /><label className="school-consent"><input required type="checkbox" checked={contact.consent} onChange={(event) => setContact({ ...contact, consent: event.target.checked })} /><span>I agree that Wendy may contact me about this private planning request. I understand that travel is not reserved until Wendy confirms a live quote and I approve it.</span></label><button className="button-submit" type="submit" disabled={submit.isPending}>{submit.isPending ? "Sending your details…" : "Send my traveler profile"} <span aria-hidden="true">↗</span></button>{submit.error && <p className="form-error" role="alert">Something interrupted your submission. Please try again or contact Wendy directly.</p>}</form></div></section></SiteShell>;
}

function Field({ id, label, value, onChange, required, wide, text, type = "text" }: { id: string; label: string; value: string; onChange: (value: string) => void; required?: boolean; wide?: boolean; text?: boolean; type?: string }) {
  return <div className={`form-field${wide ? " form-field--wide" : ""}`}><label htmlFor={id}>{label}{required ? " *" : ""}</label>{text ? <textarea id={id} value={value} onChange={(event) => onChange(event.target.value)} /> : <input id={id} type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)} />}</div>;
}
