import { useState } from "react";
import WendyShell from "./WendyShell";
import { trpc } from "@/lib/trpc";

export default function WendyLibrary() {
  const [showForm, setShowForm] = useState(false);
  const crm = trpc.crm.dashboard.useQuery();
  if (crm.isLoading || !crm.data) return <WendyShell active="/wendy/library" eyebrow="Approved content" title="Library"><div className="crm-loading">Loading the library.</div></WendyShell>;
  return <WendyShell active="/wendy/library" eyebrow="Approved content" title="Library" action={<button type="button" className="crm-primary-action" onClick={() => setShowForm((value) => !value)}>{showForm ? "Close" : "Add experience"} <span aria-hidden="true">+</span></button>}><section className="crm-section-clean"><div className="crm-section-clean__heading"><div><p className="eyebrow">Reusable foundations</p><h2>Approved ship and itinerary details, ready for the right client.</h2></div><p>The library is not a pipeline. It stores content Wendy can select while building a private proposal.</p></div>{showForm && <ExperienceForm onSaved={() => { setShowForm(false); crm.refetch(); }} />}<div className="library-grid">{crm.data.experiences.map((experience) => <article key={experience.id}>{experience.heroImageUrl ? <img src={experience.heroImageUrl} alt={experience.heroImageAlt || experience.shipName} /> : <div className="library-image-placeholder" />}<div><span>{experience.status}</span><h3>{experience.shipName}</h3><p>{experience.cruiseLine}</p><strong>{experience.sailingSummary}</strong><small>{experience.groupName || experience.embarkPort}</small></div></article>)}</div></section></WendyShell>;
}

function ExperienceForm({ onSaved }: { onSaved: () => void }) { const [form, setForm] = useState({ title: "", slug: "", cruiseLine: "", shipName: "", embarkPort: "", sailingSummary: "", groupName: "", publicSummary: "", roomGuidance: "" }); const create = trpc.crm.createExperience.useMutation({ onSuccess: onSaved }); return <section className="focus-form focus-form--wide library-create"><div><p className="eyebrow">New library item</p><h2>Save a reusable cruise foundation.</h2></div><form onSubmit={(event) => { event.preventDefault(); create.mutate({ ...form, heroImageUrl: "", heroImageAlt: "", status: "draft" }); }}><div className="form-grid"><LInput id="experience-title" label="Experience title" value={form.title} onChange={(value) => setForm({ ...form, title: value })} /><LInput id="experience-slug" label="Library identifier" value={form.slug} onChange={(value) => setForm({ ...form, slug: value })} /><LInput id="experience-line" label="Cruise line" value={form.cruiseLine} onChange={(value) => setForm({ ...form, cruiseLine: value })} /><LInput id="experience-ship" label="Ship" value={form.shipName} onChange={(value) => setForm({ ...form, shipName: value })} /><LInput id="experience-port" label="Embarkation port" value={form.embarkPort} onChange={(value) => setForm({ ...form, embarkPort: value })} /><LInput id="experience-sailing" label="Sailing date or timing" value={form.sailingSummary} onChange={(value) => setForm({ ...form, sailingSummary: value })} /><LInput id="experience-group" label="Group or occasion" value={form.groupName} onChange={(value) => setForm({ ...form, groupName: value })} wide /><LInput id="experience-summary" label="Approved summary" value={form.publicSummary} onChange={(value) => setForm({ ...form, publicSummary: value })} area wide /><LInput id="experience-room" label="Room guidance" value={form.roomGuidance} onChange={(value) => setForm({ ...form, roomGuidance: value })} area wide /></div><button className="crm-primary-action" type="submit" disabled={create.isPending}>Save experience draft</button></form></section>; }
function LInput({ id, label, value, onChange, wide, area }: { id: string; label: string; value: string; onChange: (value: string) => void; wide?: boolean; area?: boolean }) { return <div className={`form-field${wide ? " form-field--wide" : ""}`}><label htmlFor={id}>{label}</label>{area ? <textarea id={id} value={value} onChange={(event) => onChange(event.target.value)} /> : <input id={id} value={value} onChange={(event) => onChange(event.target.value)} />}</div>; }
