import { useMemo, useState } from "react";
import WendyShell from "./WendyShell";
import { Calendar } from "@/components/ui/calendar";
import { trpc } from "@/lib/trpc";

type Appointment = { id: number; title: string; startsAt: Date; durationMinutes: number; attendeeName: string; attendeeEmail: string; attendeePhone: string | null; clientMessage: string | null; advisorNotes: string | null; status: "scheduled" | "completed" | "cancelled"; calendarSyncStatus: "not_connected" | "ready_to_sync" | "synced" | "sync_failed"; meetingUrl: string | null };
type AvailabilityBlock = { id: number; title: string; startsAt: Date; endsAt: Date; status: "available" | "unavailable"; notes: string | null };

function dayKey(value: Date) { return `${value.getFullYear()}-${value.getMonth()}-${value.getDate()}`; }
function localInput(value: Date) { const offset = value.getTimezoneOffset() * 60_000; return new Date(value.getTime() - offset).toISOString().slice(0, 16); }

export default function WendyCalendar() {
  const crm = trpc.crm.dashboard.useQuery();
  const [selectedDay, setSelectedDay] = useState(() => new Date());
  const createBlock = trpc.crm.createAvailabilityBlock.useMutation({ onSuccess: () => crm.refetch() });
  const deleteBlock = trpc.crm.deleteAvailabilityBlock.useMutation({ onSuccess: () => crm.refetch() });
  const appointments = (crm.data?.appointments || []) as Appointment[];
  const blocks = (crm.data?.availabilityBlocks || []) as AvailabilityBlock[];
  const selectedKey = dayKey(selectedDay);
  const dailyAppointments = useMemo(() => appointments.filter((appointment) => dayKey(new Date(appointment.startsAt)) === selectedKey), [appointments, selectedKey]);
  const dailyBlocks = useMemo(() => blocks.filter((block) => dayKey(new Date(block.startsAt)) === selectedKey), [blocks, selectedKey]);

  if (crm.isLoading || !crm.data) return <WendyShell active="/wendy/calendar" eyebrow="Schedule" title="Calendar"><div className="crm-loading">Loading calendar.</div></WendyShell>;

  return <WendyShell active="/wendy/calendar" eyebrow="Schedule" title="Calendar">
    <section className="calendar-ready-banner"><div><p className="eyebrow">Local planning calendar</p><h2>Your schedule, ready for Google later.</h2><p>Appointments and availability blocks are saved in Wendy’s workspace. Google Calendar, Google Meet, and automatic client invitations are not connected yet.</p></div><span>Google sync inactive</span></section>
    <section className="calendar-workspace">
      <article className="calendar-panel"><Calendar mode="single" selected={selectedDay} onSelect={(day) => day && setSelectedDay(day)} modifiers={{ appointment: appointments.map((item) => new Date(item.startsAt)), unavailable: blocks.filter((item) => item.status === "unavailable").map((item) => new Date(item.startsAt)) }} classNames={{ day: "calendar-panel__day" }} /><p className="calendar-legend"><span><i className="is-appointment" />Scheduled call</span><span><i className="is-unavailable" />Unavailable</span></p></article>
      <article className="calendar-day-card"><header><p className="eyebrow">Selected day</p><h2>{selectedDay.toLocaleDateString(undefined, { weekday: "long", month: "long", day: "numeric" })}</h2></header>{dailyAppointments.length || dailyBlocks.length ? <div className="calendar-day-list">{dailyAppointments.map((appointment) => <section key={`appointment-${appointment.id}`} className="calendar-entry calendar-entry--appointment"><span>{new Date(appointment.startsAt).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })}</span><div><strong>{appointment.title}</strong><p>{appointment.attendeeName} · {appointment.durationMinutes} minutes</p><small>Google Calendar and Meet pending connection</small></div></section>)}{dailyBlocks.map((block) => <section key={`block-${block.id}`} className={`calendar-entry calendar-entry--${block.status}`}><span>{new Date(block.startsAt).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })}</span><div><strong>{block.title}</strong><p>Until {new Date(block.endsAt).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })}</p>{block.notes ? <small>{block.notes}</small> : null}</div><button className="crm-text-link" type="button" onClick={() => deleteBlock.mutate({ id: block.id })}>Remove</button></section>)}</div> : <p className="crm-empty-clean">Nothing is scheduled locally for this day.</p>}</article>
    </section>
    <section className="availability-editor"><div><p className="eyebrow">Availability</p><h2>Block time or mark an opening.</h2><p>These local blocks prepare Wendy’s availability for a later booking experience. They do not open client booking or change Google Calendar.</p></div><form onSubmit={(event) => { event.preventDefault(); const values = new FormData(event.currentTarget); const startsAt = new Date(String(values.get("startsAt") || "")); const endsAt = new Date(String(values.get("endsAt") || "")); if (Number.isNaN(startsAt.getTime()) || Number.isNaN(endsAt.getTime())) return; createBlock.mutate({ title: String(values.get("title") || ""), startsAt: startsAt.toISOString(), endsAt: endsAt.toISOString(), status: String(values.get("status")) as "available" | "unavailable", notes: String(values.get("notes") || "") }); event.currentTarget.reset(); }}><div className="form-grid"><div className="form-field"><label htmlFor="availability-title">Label</label><input id="availability-title" name="title" required placeholder="Personal commitment" /></div><div className="form-field"><label htmlFor="availability-status">Status</label><select id="availability-status" name="status" defaultValue="unavailable"><option value="unavailable">Unavailable</option><option value="available">Available</option></select></div><div className="form-field"><label htmlFor="availability-start">Starts</label><input id="availability-start" name="startsAt" type="datetime-local" defaultValue={localInput(selectedDay)} required /></div><div className="form-field"><label htmlFor="availability-end">Ends</label><input id="availability-end" name="endsAt" type="datetime-local" defaultValue={localInput(new Date(selectedDay.getTime() + 60 * 60 * 1000))} required /></div><div className="form-field form-field--wide"><label htmlFor="availability-notes">Notes</label><textarea id="availability-notes" name="notes" placeholder="Optional private note" /></div></div><div className="stage-action-bar"><button className="crm-primary-action" type="submit" disabled={createBlock.isPending}>Save availability block</button>{createBlock.error ? <p className="stage-error">{createBlock.error.message}</p> : null}</div></form></section>
    <section className="calendar-upcoming"><header><div><p className="eyebrow">Upcoming calls</p><h2>Saved discovery appointments.</h2></div><p>Client invitations and meeting links will appear here after Google is connected.</p></header><div>{appointments.length ? appointments.filter((item) => item.status === "scheduled").map((appointment) => <article key={appointment.id}><time>{new Date(appointment.startsAt).toLocaleDateString(undefined, { month: "short", day: "numeric" })}<strong>{new Date(appointment.startsAt).toLocaleTimeString(undefined, { hour: "numeric", minute: "2-digit" })}</strong></time><div><strong>{appointment.title}</strong><span>{appointment.attendeeName} · {appointment.attendeeEmail}</span></div><small>Google sync inactive</small></article>) : <p className="crm-empty-clean">No local discovery appointments yet.</p>}</div></section>
  </WendyShell>;
}
